site_name: Developers
site_url: https://developers.photos.network
repo_url: https://github.com/photos.network/developers.photos.network
repo_name: photos.network
site_description: "https://photos.network is an open source project for self hosted photo management."
site_author: "Stürmer, Benjamin"
copyright: 'Copyright &copy; 2020 <a href="https://photos.network">Photos network developers</a>'

extra_css:
  - _css/extra.css

extra_javascript:
  - _js/extra.js

extra:
  version: 0.1.0
  social:
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/thebino/photos
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/photos.network

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

strict: true

# Navigation
nav:
  - 'Home': 'index.md'
#  - 'Supervisor': 'supervisor/index.md'
  - 'Core':
      - 'Getting started': 'core/index.md'
  - 'Addons':
      - 'Create an addon': 'addons/index.md'
      - 'api': 'addons/api.md'
      - 'metadata': 'addons/metadata.md'
      - 'nextcloud': 'addons/nextcloud.md'
      - 'places365': 'addons/places365.md'
  - 'Frontend': 'frontend/index.md'
  - 'Mobile':
      - 'General': 'mobile/index.md'
      - 'Android': 'mobile/android/index.md'
      - 'iOS': 'mobile/ios/index.md'

# Theme
theme:
  name: material
  custom_dir: overrides

  palette:
    - scheme: preference
      primary: blue
      accent: pink

  # disable font loading to comply GDPR
  font: false

  icon:
    logo: material/image
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.tabs
