site_name: Developers
site_url: https://developers.photos.network
repo_url: https://github.com/photos-network/developers.photos.network
edit_uri: edit/development/docs/
repo_name: photos.network
site_description: "https://photos.network is a free and open source, privacy first, self-hosted photo storage and sharing service."
site_author: "Stürmer, Benjamin"
copyright: 'Copyright &copy; 2020 <a href="https://photos.network">Photos network developers</a>'

plugins:
  - render_swagger

extra_css:
  - _css/extra.css

extra_javascript:
  - _js/extra.js

extra:
  version: 0.1.0
  social:
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/thebino/photos
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/photosnetwork

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

strict: true

# Navigation
nav:
  - "Home": "index.md"
  - "Getting started":
      - "Overview": "overview.md"
  - "Core":
      - "Getting started": "core/index.md"
      - "Structure": "core/structure.md"
      - "Authentication": "core/authentication.md"
      - "Authorization flow": "core/authentication_flow.md"
      - "Authorization": "core/authorization.md"
      - "User management": "core/user_management.md"
      - "Configuration": "core/configuration.md"
  - "Plugins":
      - "Create an addon": "plugins/index.md"
      - "api": "plugins/api.md"
      - "metadata": "plugins/metadata.md"
      - "nextcloud": "plugins/nextcloud.md"
      - "places365": "plugins/places365.md"
  - "Frontend":
      - "Getting started": "frontend/index.md"
      - "Grid": "frontend/grid.md"
      - "Albums": "frontend/albums.md"
      - "Map": "frontend/map.md"
      - "Search": "frontend/search.md"
      - "Details": "frontend/details.md"
      - "Share": "frontend/share.md"
  - "Mobile":
      - "General": "mobile/index.md"
      - "Android": "mobile/android/index.md"
      - "iOS": "mobile/ios/index.md"
  - "FAQ": "faq.md"

# Theme
theme:
  name: material
  custom_dir: overrides

  palette:
    scheme: preference
    primary: blue
    accent: pink

  # disable font loading to comply GDPR
  font: false

  icon:
    logo: material/image
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.tabs
